// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ClipboardItem {
  final String id;
  final String contentType;
  final String preview;
  final String? content;
  final BigInt timestamp;
  final BigInt size;
  final bool pinned;

  const ClipboardItem({
    required this.id,
    required this.contentType,
    required this.preview,
    this.content,
    required this.timestamp,
    required this.size,
    required this.pinned,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      contentType.hashCode ^
      preview.hashCode ^
      content.hashCode ^
      timestamp.hashCode ^
      size.hashCode ^
      pinned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClipboardItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          contentType == other.contentType &&
          preview == other.preview &&
          content == other.content &&
          timestamp == other.timestamp &&
          size == other.size &&
          pinned == other.pinned;
}
