// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_icon`, `get_app_aliases`, `get_data_dir`, `hicon_to_image`, `is_system_exe`, `read_custom_apps`, `record_usage`, `scan_exe_in_dir`, `scan_program_files`, `scan_shortcuts`, `scan_system_tools`, `validate_path`, `write_custom_apps`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AppCache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<List<AppInfo>> getInstalledApps() =>
    RustLib.instance.api.crateApiAppGetInstalledApps();

Future<void> launchApp({required String path}) =>
    RustLib.instance.api.crateApiAppLaunchApp(path: path);

Future<Map<String, AppUsage>> getAppUsage() =>
    RustLib.instance.api.crateApiAppGetAppUsage();

Future<void> openFile({required String path}) =>
    RustLib.instance.api.crateApiAppOpenFile(path: path);

Future<void> showInFolder({required String path}) =>
    RustLib.instance.api.crateApiAppShowInFolder(path: path);

Future<String?> getAppIconBase64({required String path}) =>
    RustLib.instance.api.crateApiAppGetAppIconBase64(path: path);

Future<List<CustomApp>> getCustomApps() =>
    RustLib.instance.api.crateApiAppGetCustomApps();

Future<void> addCustomApp({required String name, required String path}) =>
    RustLib.instance.api.crateApiAppAddCustomApp(name: name, path: path);

Future<void> removeCustomApp({required String path}) =>
    RustLib.instance.api.crateApiAppRemoveCustomApp(path: path);

Future<bool> isAutostartEnabled() =>
    RustLib.instance.api.crateApiAppIsAutostartEnabled();

Future<void> setAutostart({required bool enabled}) =>
    RustLib.instance.api.crateApiAppSetAutostart(enabled: enabled);

class AppInfo {
  final String name;
  final String path;
  final String? icon;
  final List<String> aliases;

  const AppInfo({
    required this.name,
    required this.path,
    this.icon,
    required this.aliases,
  });

  @override
  int get hashCode =>
      name.hashCode ^ path.hashCode ^ icon.hashCode ^ aliases.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          icon == other.icon &&
          aliases == other.aliases;
}

class AppUsage {
  final int count;
  final PlatformInt64 lastUsed;

  const AppUsage({required this.count, required this.lastUsed});

  static Future<AppUsage> default_() =>
      RustLib.instance.api.crateApiAppAppUsageDefault();

  @override
  int get hashCode => count.hashCode ^ lastUsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppUsage &&
          runtimeType == other.runtimeType &&
          count == other.count &&
          lastUsed == other.lastUsed;
}

class CustomApp {
  final String name;
  final String path;

  const CustomApp({required this.name, required this.path});

  @override
  int get hashCode => name.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomApp &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path;
}
