// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../clipboard_impl/history.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取剪贴板历史记录
Future<List<ClipboardItem>> getClipboardHistory() =>
    RustLib.instance.api.crateApiClipboardGetClipboardHistory();

/// 获取剪贴板图片的原始大小 base64（用于复制粘贴）
Future<String?> getClipboardImageFullBase64({required String id}) =>
    RustLib.instance.api.crateApiClipboardGetClipboardImageFullBase64(id: id);

/// 删除指定剪贴板记录
Future<void> deleteClipboardItem({required String id}) =>
    RustLib.instance.api.crateApiClipboardDeleteClipboardItem(id: id);

/// 清空剪贴板历史
Future<void> clearClipboardHistory() =>
    RustLib.instance.api.crateApiClipboardClearClipboardHistory();

/// 切换固定状态
Future<void> togglePinClipboardItem({required String id}) =>
    RustLib.instance.api.crateApiClipboardTogglePinClipboardItem(id: id);

/// 复制内容到剪贴板
Future<void> copyToClipboard({required String content}) =>
    RustLib.instance.api.crateApiClipboardCopyToClipboard(content: content);

/// 复制图片到剪贴板（传入 PNG base64 数据）
Future<void> copyImageToClipboard({required String base64Data}) => RustLib
    .instance
    .api
    .crateApiClipboardCopyImageToClipboard(base64Data: base64Data);
