// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_docx_text`, `extract_pdf_text`, `extract_pptx_text`, `extract_text_from_stream`, `extract_xlsx_text`, `extract_xml_text_content`, `is_leap_year`, `is_likely_text`, `parse_shared_strings`, `parse_xlsx_sheet`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

/// 使用 Everything HTTP API 搜索文件
Future<List<FileResult>> searchFiles({
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiFileSearchFiles(query: query, limit: limit);

/// 获取文件预览
Future<FilePreviewResult?> getFilePreview({required String path}) =>
    RustLib.instance.api.crateApiFileGetFilePreview(path: path);

/// 获取图片缩略图（返回 base64）
Future<String?> getImageThumbnail({required String path}) =>
    RustLib.instance.api.crateApiFileGetImageThumbnail(path: path);

class FilePreviewResult {
  final String previewType;
  final String? content;
  final BigInt? totalLines;
  final BigInt size;
  final String modified;
  final String extension_;

  const FilePreviewResult({
    required this.previewType,
    this.content,
    this.totalLines,
    required this.size,
    required this.modified,
    required this.extension_,
  });

  @override
  int get hashCode =>
      previewType.hashCode ^
      content.hashCode ^
      totalLines.hashCode ^
      size.hashCode ^
      modified.hashCode ^
      extension_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FilePreviewResult &&
          runtimeType == other.runtimeType &&
          previewType == other.previewType &&
          content == other.content &&
          totalLines == other.totalLines &&
          size == other.size &&
          modified == other.modified &&
          extension_ == other.extension_;
}

class FileResult {
  final String name;
  final String path;
  final BigInt size;
  final String modified;
  final String resultType;

  const FileResult({
    required this.name,
    required this.path,
    required this.size,
    required this.modified,
    required this.resultType,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      size.hashCode ^
      modified.hashCode ^
      resultType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileResult &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          size == other.size &&
          modified == other.modified &&
          resultType == other.resultType;
}
