// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化后端：启动剪贴板监听、注册全局热键
Future<void> initBackend() => RustLib.instance.api.crateApiWindowInitBackend();

/// 关闭后端：停止剪贴板监听
Future<void> shutdownBackend() =>
    RustLib.instance.api.crateApiWindowShutdownBackend();

/// Dart 端轮询：是否有热键触发事件待处理
Future<bool> consumeHotkeyFlag() =>
    RustLib.instance.api.crateApiWindowConsumeHotkeyFlag();

/// 应用 DWM 无边框毛玻璃样式
/// `hwnd_value` 是 Flutter 窗口的原生 HWND 的 isize 表示
Future<void> applyDwmBorderless({required PlatformInt64 hwndValue}) =>
    RustLib.instance.api.crateApiWindowApplyDwmBorderless(hwndValue: hwndValue);

/// 仅应用 DWM 属性，不调用 SetWindowPos（避免窗口闪烁）
Future<void> refreshDwmAttributes({required PlatformInt64 hwndValue}) => RustLib
    .instance
    .api
    .crateApiWindowRefreshDwmAttributes(hwndValue: hwndValue);
