// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/app.dart';
import 'api/clipboard.dart';
import 'api/file.dart';
import 'api/window.dart';
import 'clipboard_impl/history.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, AppUsage> dco_decode_Map_String_app_usage_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppInfo dco_decode_app_info(dynamic raw);

  @protected
  AppUsage dco_decode_app_usage(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FilePreviewResult dco_decode_box_autoadd_file_preview_result(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  ClipboardItem dco_decode_clipboard_item(dynamic raw);

  @protected
  CustomApp dco_decode_custom_app(dynamic raw);

  @protected
  FilePreviewResult dco_decode_file_preview_result(dynamic raw);

  @protected
  FileResult dco_decode_file_result(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AppInfo> dco_decode_list_app_info(dynamic raw);

  @protected
  List<ClipboardItem> dco_decode_list_clipboard_item(dynamic raw);

  @protected
  List<CustomApp> dco_decode_list_custom_app(dynamic raw);

  @protected
  List<FileResult> dco_decode_list_file_result(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, AppUsage)> dco_decode_list_record_string_app_usage(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FilePreviewResult? dco_decode_opt_box_autoadd_file_preview_result(
    dynamic raw,
  );

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  (String, AppUsage) dco_decode_record_string_app_usage(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Map<String, AppUsage> sse_decode_Map_String_app_usage_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppInfo sse_decode_app_info(SseDeserializer deserializer);

  @protected
  AppUsage sse_decode_app_usage(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FilePreviewResult sse_decode_box_autoadd_file_preview_result(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  ClipboardItem sse_decode_clipboard_item(SseDeserializer deserializer);

  @protected
  CustomApp sse_decode_custom_app(SseDeserializer deserializer);

  @protected
  FilePreviewResult sse_decode_file_preview_result(
    SseDeserializer deserializer,
  );

  @protected
  FileResult sse_decode_file_result(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AppInfo> sse_decode_list_app_info(SseDeserializer deserializer);

  @protected
  List<ClipboardItem> sse_decode_list_clipboard_item(
    SseDeserializer deserializer,
  );

  @protected
  List<CustomApp> sse_decode_list_custom_app(SseDeserializer deserializer);

  @protected
  List<FileResult> sse_decode_list_file_result(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, AppUsage)> sse_decode_list_record_string_app_usage(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FilePreviewResult? sse_decode_opt_box_autoadd_file_preview_result(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  (String, AppUsage) sse_decode_record_string_app_usage(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_app_usage_None(
    Map<String, AppUsage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_info(AppInfo self, SseSerializer serializer);

  @protected
  void sse_encode_app_usage(AppUsage self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_file_preview_result(
    FilePreviewResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_clipboard_item(ClipboardItem self, SseSerializer serializer);

  @protected
  void sse_encode_custom_app(CustomApp self, SseSerializer serializer);

  @protected
  void sse_encode_file_preview_result(
    FilePreviewResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_result(FileResult self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_info(List<AppInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_clipboard_item(
    List<ClipboardItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_custom_app(
    List<CustomApp> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_result(
    List<FileResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_app_usage(
    List<(String, AppUsage)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_file_preview_result(
    FilePreviewResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_app_usage(
    (String, AppUsage) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
