// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/app.dart';
import 'api/clipboard.dart';
import 'api/file.dart';
import 'api/window.dart';
import 'clipboard_impl/history.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1787455972;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'wtools_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiAppAddCustomApp({
    required String name,
    required String path,
  });

  Future<AppUsage> crateApiAppAppUsageDefault();

  Future<void> crateApiWindowApplyDwmBorderless({
    required PlatformInt64 hwndValue,
  });

  Future<void> crateApiClipboardClearClipboardHistory();

  Future<bool> crateApiWindowConsumeHotkeyFlag();

  Future<void> crateApiClipboardCopyImageToClipboard({
    required String base64Data,
  });

  Future<void> crateApiClipboardCopyToClipboard({required String content});

  Future<void> crateApiClipboardDeleteClipboardItem({required String id});

  Future<String?> crateApiAppGetAppIconBase64({required String path});

  Future<Map<String, AppUsage>> crateApiAppGetAppUsage();

  Future<List<ClipboardItem>> crateApiClipboardGetClipboardHistory();

  Future<String?> crateApiClipboardGetClipboardImageFullBase64({
    required String id,
  });

  Future<List<CustomApp>> crateApiAppGetCustomApps();

  Future<FilePreviewResult?> crateApiFileGetFilePreview({required String path});

  Future<String?> crateApiFileGetImageThumbnail({required String path});

  Future<List<AppInfo>> crateApiAppGetInstalledApps();

  Future<void> crateApiWindowInitBackend();

  Future<bool> crateApiAppIsAutostartEnabled();

  Future<void> crateApiAppLaunchApp({required String path});

  Future<void> crateApiAppOpenFile({required String path});

  Future<void> crateApiWindowRefreshDwmAttributes({
    required PlatformInt64 hwndValue,
  });

  Future<void> crateApiAppRemoveCustomApp({required String path});

  Future<List<FileResult>> crateApiFileSearchFiles({
    required String query,
    required int limit,
  });

  Future<void> crateApiAppSetAutostart({required bool enabled});

  Future<void> crateApiAppShowInFolder({required String path});

  Future<void> crateApiWindowShutdownBackend();

  Future<void> crateApiClipboardTogglePinClipboardItem({required String id});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiAppAddCustomApp({
    required String name,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppAddCustomAppConstMeta,
        argValues: [name, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppAddCustomAppConstMeta => const TaskConstMeta(
    debugName: "add_custom_app",
    argNames: ["name", "path"],
  );

  @override
  Future<AppUsage> crateApiAppAppUsageDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_usage,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppAppUsageDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppAppUsageDefaultConstMeta =>
      const TaskConstMeta(debugName: "app_usage_default", argNames: []);

  @override
  Future<void> crateApiWindowApplyDwmBorderless({
    required PlatformInt64 hwndValue,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_isize(hwndValue, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWindowApplyDwmBorderlessConstMeta,
        argValues: [hwndValue],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWindowApplyDwmBorderlessConstMeta =>
      const TaskConstMeta(
        debugName: "apply_dwm_borderless",
        argNames: ["hwndValue"],
      );

  @override
  Future<void> crateApiClipboardClearClipboardHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipboardClearClipboardHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipboardClearClipboardHistoryConstMeta =>
      const TaskConstMeta(debugName: "clear_clipboard_history", argNames: []);

  @override
  Future<bool> crateApiWindowConsumeHotkeyFlag() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWindowConsumeHotkeyFlagConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWindowConsumeHotkeyFlagConstMeta =>
      const TaskConstMeta(debugName: "consume_hotkey_flag", argNames: []);

  @override
  Future<void> crateApiClipboardCopyImageToClipboard({
    required String base64Data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base64Data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipboardCopyImageToClipboardConstMeta,
        argValues: [base64Data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipboardCopyImageToClipboardConstMeta =>
      const TaskConstMeta(
        debugName: "copy_image_to_clipboard",
        argNames: ["base64Data"],
      );

  @override
  Future<void> crateApiClipboardCopyToClipboard({required String content}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipboardCopyToClipboardConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipboardCopyToClipboardConstMeta =>
      const TaskConstMeta(
        debugName: "copy_to_clipboard",
        argNames: ["content"],
      );

  @override
  Future<void> crateApiClipboardDeleteClipboardItem({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipboardDeleteClipboardItemConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipboardDeleteClipboardItemConstMeta =>
      const TaskConstMeta(debugName: "delete_clipboard_item", argNames: ["id"]);

  @override
  Future<String?> crateApiAppGetAppIconBase64({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppGetAppIconBase64ConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetAppIconBase64ConstMeta =>
      const TaskConstMeta(debugName: "get_app_icon_base64", argNames: ["path"]);

  @override
  Future<Map<String, AppUsage>> crateApiAppGetAppUsage() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Map_String_app_usage_None,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppGetAppUsageConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetAppUsageConstMeta =>
      const TaskConstMeta(debugName: "get_app_usage", argNames: []);

  @override
  Future<List<ClipboardItem>> crateApiClipboardGetClipboardHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_clipboard_item,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipboardGetClipboardHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipboardGetClipboardHistoryConstMeta =>
      const TaskConstMeta(debugName: "get_clipboard_history", argNames: []);

  @override
  Future<String?> crateApiClipboardGetClipboardImageFullBase64({
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipboardGetClipboardImageFullBase64ConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipboardGetClipboardImageFullBase64ConstMeta =>
      const TaskConstMeta(
        debugName: "get_clipboard_image_full_base64",
        argNames: ["id"],
      );

  @override
  Future<List<CustomApp>> crateApiAppGetCustomApps() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_custom_app,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppGetCustomAppsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetCustomAppsConstMeta =>
      const TaskConstMeta(debugName: "get_custom_apps", argNames: []);

  @override
  Future<FilePreviewResult?> crateApiFileGetFilePreview({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_file_preview_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFileGetFilePreviewConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileGetFilePreviewConstMeta =>
      const TaskConstMeta(debugName: "get_file_preview", argNames: ["path"]);

  @override
  Future<String?> crateApiFileGetImageThumbnail({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFileGetImageThumbnailConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileGetImageThumbnailConstMeta =>
      const TaskConstMeta(debugName: "get_image_thumbnail", argNames: ["path"]);

  @override
  Future<List<AppInfo>> crateApiAppGetInstalledApps() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_app_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppGetInstalledAppsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetInstalledAppsConstMeta =>
      const TaskConstMeta(debugName: "get_installed_apps", argNames: []);

  @override
  Future<void> crateApiWindowInitBackend() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWindowInitBackendConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWindowInitBackendConstMeta =>
      const TaskConstMeta(debugName: "init_backend", argNames: []);

  @override
  Future<bool> crateApiAppIsAutostartEnabled() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppIsAutostartEnabledConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppIsAutostartEnabledConstMeta =>
      const TaskConstMeta(debugName: "is_autostart_enabled", argNames: []);

  @override
  Future<void> crateApiAppLaunchApp({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppLaunchAppConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppLaunchAppConstMeta =>
      const TaskConstMeta(debugName: "launch_app", argNames: ["path"]);

  @override
  Future<void> crateApiAppOpenFile({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppOpenFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppOpenFileConstMeta =>
      const TaskConstMeta(debugName: "open_file", argNames: ["path"]);

  @override
  Future<void> crateApiWindowRefreshDwmAttributes({
    required PlatformInt64 hwndValue,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_isize(hwndValue, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWindowRefreshDwmAttributesConstMeta,
        argValues: [hwndValue],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWindowRefreshDwmAttributesConstMeta =>
      const TaskConstMeta(
        debugName: "refresh_dwm_attributes",
        argNames: ["hwndValue"],
      );

  @override
  Future<void> crateApiAppRemoveCustomApp({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppRemoveCustomAppConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppRemoveCustomAppConstMeta =>
      const TaskConstMeta(debugName: "remove_custom_app", argNames: ["path"]);

  @override
  Future<List<FileResult>> crateApiFileSearchFiles({
    required String query,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_file_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSearchFilesConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSearchFilesConstMeta => const TaskConstMeta(
    debugName: "search_files",
    argNames: ["query", "limit"],
  );

  @override
  Future<void> crateApiAppSetAutostart({required bool enabled}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppSetAutostartConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppSetAutostartConstMeta =>
      const TaskConstMeta(debugName: "set_autostart", argNames: ["enabled"]);

  @override
  Future<void> crateApiAppShowInFolder({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppShowInFolderConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppShowInFolderConstMeta =>
      const TaskConstMeta(debugName: "show_in_folder", argNames: ["path"]);

  @override
  Future<void> crateApiWindowShutdownBackend() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWindowShutdownBackendConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWindowShutdownBackendConstMeta =>
      const TaskConstMeta(debugName: "shutdown_backend", argNames: []);

  @override
  Future<void> crateApiClipboardTogglePinClipboardItem({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipboardTogglePinClipboardItemConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipboardTogglePinClipboardItemConstMeta =>
      const TaskConstMeta(
        debugName: "toggle_pin_clipboard_item",
        argNames: ["id"],
      );

  @protected
  Map<String, AppUsage> dco_decode_Map_String_app_usage_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_app_usage(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppInfo dco_decode_app_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AppInfo(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      icon: dco_decode_opt_String(arr[2]),
      aliases: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  AppUsage dco_decode_app_usage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AppUsage(
      count: dco_decode_u_32(arr[0]),
      lastUsed: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FilePreviewResult dco_decode_box_autoadd_file_preview_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_file_preview_result(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  ClipboardItem dco_decode_clipboard_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ClipboardItem(
      id: dco_decode_String(arr[0]),
      contentType: dco_decode_String(arr[1]),
      preview: dco_decode_String(arr[2]),
      content: dco_decode_opt_String(arr[3]),
      timestamp: dco_decode_u_64(arr[4]),
      size: dco_decode_usize(arr[5]),
      pinned: dco_decode_bool(arr[6]),
    );
  }

  @protected
  CustomApp dco_decode_custom_app(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CustomApp(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
    );
  }

  @protected
  FilePreviewResult dco_decode_file_preview_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FilePreviewResult(
      previewType: dco_decode_String(arr[0]),
      content: dco_decode_opt_String(arr[1]),
      totalLines: dco_decode_opt_box_autoadd_usize(arr[2]),
      size: dco_decode_u_64(arr[3]),
      modified: dco_decode_String(arr[4]),
      extension_: dco_decode_String(arr[5]),
    );
  }

  @protected
  FileResult dco_decode_file_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FileResult(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      size: dco_decode_u_64(arr[2]),
      modified: dco_decode_String(arr[3]),
      resultType: dco_decode_String(arr[4]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AppInfo> dco_decode_list_app_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_info).toList();
  }

  @protected
  List<ClipboardItem> dco_decode_list_clipboard_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_clipboard_item).toList();
  }

  @protected
  List<CustomApp> dco_decode_list_custom_app(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_custom_app).toList();
  }

  @protected
  List<FileResult> dco_decode_list_file_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_file_result).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, AppUsage)> dco_decode_list_record_string_app_usage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_app_usage)
        .toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FilePreviewResult? dco_decode_opt_box_autoadd_file_preview_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_file_preview_result(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  (String, AppUsage) dco_decode_record_string_app_usage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_app_usage(arr[1]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Map<String, AppUsage> sse_decode_Map_String_app_usage_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_app_usage(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppInfo sse_decode_app_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_icon = sse_decode_opt_String(deserializer);
    var var_aliases = sse_decode_list_String(deserializer);
    return AppInfo(
      name: var_name,
      path: var_path,
      icon: var_icon,
      aliases: var_aliases,
    );
  }

  @protected
  AppUsage sse_decode_app_usage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_count = sse_decode_u_32(deserializer);
    var var_lastUsed = sse_decode_i_64(deserializer);
    return AppUsage(count: var_count, lastUsed: var_lastUsed);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FilePreviewResult sse_decode_box_autoadd_file_preview_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_file_preview_result(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  ClipboardItem sse_decode_clipboard_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_contentType = sse_decode_String(deserializer);
    var var_preview = sse_decode_String(deserializer);
    var var_content = sse_decode_opt_String(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_size = sse_decode_usize(deserializer);
    var var_pinned = sse_decode_bool(deserializer);
    return ClipboardItem(
      id: var_id,
      contentType: var_contentType,
      preview: var_preview,
      content: var_content,
      timestamp: var_timestamp,
      size: var_size,
      pinned: var_pinned,
    );
  }

  @protected
  CustomApp sse_decode_custom_app(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    return CustomApp(name: var_name, path: var_path);
  }

  @protected
  FilePreviewResult sse_decode_file_preview_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_previewType = sse_decode_String(deserializer);
    var var_content = sse_decode_opt_String(deserializer);
    var var_totalLines = sse_decode_opt_box_autoadd_usize(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_modified = sse_decode_String(deserializer);
    var var_extension_ = sse_decode_String(deserializer);
    return FilePreviewResult(
      previewType: var_previewType,
      content: var_content,
      totalLines: var_totalLines,
      size: var_size,
      modified: var_modified,
      extension_: var_extension_,
    );
  }

  @protected
  FileResult sse_decode_file_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_modified = sse_decode_String(deserializer);
    var var_resultType = sse_decode_String(deserializer);
    return FileResult(
      name: var_name,
      path: var_path,
      size: var_size,
      modified: var_modified,
      resultType: var_resultType,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AppInfo> sse_decode_list_app_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ClipboardItem> sse_decode_list_clipboard_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ClipboardItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_clipboard_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<CustomApp> sse_decode_list_custom_app(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CustomApp>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_custom_app(deserializer));
    }
    return ans_;
  }

  @protected
  List<FileResult> sse_decode_list_file_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FileResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_file_result(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, AppUsage)> sse_decode_list_record_string_app_usage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, AppUsage)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_app_usage(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FilePreviewResult? sse_decode_opt_box_autoadd_file_preview_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_file_preview_result(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, AppUsage) sse_decode_record_string_app_usage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_app_usage(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_Map_String_app_usage_None(
    Map<String, AppUsage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_app_usage(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_info(AppInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_opt_String(self.icon, serializer);
    sse_encode_list_String(self.aliases, serializer);
  }

  @protected
  void sse_encode_app_usage(AppUsage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.count, serializer);
    sse_encode_i_64(self.lastUsed, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_file_preview_result(
    FilePreviewResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_file_preview_result(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_clipboard_item(ClipboardItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.contentType, serializer);
    sse_encode_String(self.preview, serializer);
    sse_encode_opt_String(self.content, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_usize(self.size, serializer);
    sse_encode_bool(self.pinned, serializer);
  }

  @protected
  void sse_encode_custom_app(CustomApp self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
  }

  @protected
  void sse_encode_file_preview_result(
    FilePreviewResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.previewType, serializer);
    sse_encode_opt_String(self.content, serializer);
    sse_encode_opt_box_autoadd_usize(self.totalLines, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_String(self.modified, serializer);
    sse_encode_String(self.extension_, serializer);
  }

  @protected
  void sse_encode_file_result(FileResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_String(self.modified, serializer);
    sse_encode_String(self.resultType, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_app_info(List<AppInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_clipboard_item(
    List<ClipboardItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_clipboard_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_custom_app(
    List<CustomApp> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_custom_app(item, serializer);
    }
  }

  @protected
  void sse_encode_list_file_result(
    List<FileResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_file_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_app_usage(
    List<(String, AppUsage)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_app_usage(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_file_preview_result(
    FilePreviewResult? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_file_preview_result(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_app_usage(
    (String, AppUsage) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_app_usage(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
